// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shadowbase.Data;

#nullable disable

namespace shadowbase.Migrations
{
    [DbContext(typeof(ShadowbaseContext))]
    partial class ShadowbaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shadowbase.Models.Auction", b =>
                {
                    b.Property<int>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionID"));

                    b.Property<int>("AuctionStatusIDFK")
                        .HasColumnType("int");

                    b.Property<int>("AuctionTypeIDFK")
                        .HasColumnType("int");

                    b.Property<decimal>("BidLimit")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("ClientIDFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeBudget")
                        .HasColumnType("int");

                    b.Property<int>("UserIDFK")
                        .HasColumnType("int");

                    b.HasKey("AuctionID");

                    b.HasIndex("AuctionStatusIDFK");

                    b.HasIndex("AuctionTypeIDFK");

                    b.HasIndex("ClientIDFK");

                    b.HasIndex("UserIDFK");

                    b.ToTable("Auction", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.AuctionStatus", b =>
                {
                    b.Property<int>("AuctionStatusID")
                        .HasColumnType("int");

                    b.Property<string>("AuctionStatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuctionStatusID");

                    b.ToTable("AuctionStatus", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.AuctionType", b =>
                {
                    b.Property<int>("AuctionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("AuctionTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuctionTypeID");

                    b.ToTable("AuctionType", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.Bid", b =>
                {
                    b.Property<int>("BidID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidID"));

                    b.Property<int>("AuctionIDFK")
                        .HasColumnType("int");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(2, 2)");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserIDFK")
                        .HasColumnType("int");

                    b.HasKey("BidID");

                    b.HasIndex("AuctionIDFK");

                    b.HasIndex("UserIDFK");

                    b.ToTable("Bid", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayPalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeIDFK")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("UserTypeIDFK");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.Property<string>("UserTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserTypeID");

                    b.ToTable("UserType", (string)null);
                });

            modelBuilder.Entity("shadowbase.Models.Auction", b =>
                {
                    b.HasOne("shadowbase.Models.AuctionStatus", "AuctionStatus")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctionStatusIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shadowbase.Models.AuctionType", "AuctionType")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctionTypeIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shadowbase.Models.Client", "Client")
                        .WithMany("Auctions")
                        .HasForeignKey("ClientIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shadowbase.Models.User", "User")
                        .WithMany("Auctions")
                        .HasForeignKey("UserIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionStatus");

                    b.Navigation("AuctionType");

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("shadowbase.Models.Bid", b =>
                {
                    b.HasOne("shadowbase.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shadowbase.Models.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserIDFK");

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("shadowbase.Models.User", b =>
                {
                    b.HasOne("shadowbase.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("shadowbase.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("shadowbase.Models.AuctionStatus", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("shadowbase.Models.AuctionType", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("shadowbase.Models.Client", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("shadowbase.Models.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("shadowbase.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
